import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";

const SITE_NAME = "Autocaptions";
const SITE_TITLE = "Autocaptions — Free AI Captions for Any Video";
const SITE_DESCRIPTION =
  "Drop in a video, get it back with bold TikTok-style captions burned in. Word-level sync, no signup, no watermark. Free AI autocaptioning powered by Hyperclip.";

export const metadata: Metadata = {
  metadataBase: new URL("https://autocaptions.vercel.app"),
  title: {
    default: SITE_TITLE,
    template: "%s · " + SITE_NAME,
  },
  description: SITE_DESCRIPTION,
  keywords: [
    "autocaptions",
    "auto captions",
    "video captions",
    "AI captions",
    "TikTok captions",
    "burn in captions",
    "caption generator",
    "subtitle generator",
    "free caption tool",
    "Whisper captions",
    "word level captions",
  ],
  openGraph: {
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    type: "website",
    siteName: SITE_NAME,
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
  },
  robots: {
    index: true,
    follow: true,
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebApplication",
      name: SITE_NAME,
      description: SITE_DESCRIPTION,
      applicationCategory: "MultimediaApplication",
      operatingSystem: "Web",
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      featureList: [
        "AI word-level transcription",
        "Bold TikTok-style captions burned into the video",
        "No signup, no watermark",
        "Supports MP4, MOV, WebM, MKV, MPEG",
        "Up to 500MB per video",
      ],
    },
    {
      "@type": "FAQPage",
      mainEntity: [
        {
          "@type": "Question",
          name: "How long does it take to caption a video?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Most short videos (under a minute) finish in 30–90 seconds. Longer videos scale roughly with their duration. You'll see live progress as the AI works.",
          },
        },
        {
          "@type": "Question",
          name: "What video formats are supported?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "MP4, MOV, WebM, MKV, and MPEG, up to 500MB per file.",
          },
        },
        {
          "@type": "Question",
          name: "How accurate are the captions?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Captions are generated by OpenAI's Whisper model with word-level timestamps, so each word lights up in sync with the audio. Accuracy is high for clear speech; heavily accented or very noisy audio may need a manual touch-up.",
          },
        },
        {
          "@type": "Question",
          name: "Is my video stored anywhere?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "Your upload sits in temporary cloud storage only long enough for the AI to process it. The captioned download link is valid for 24 hours and then expires.",
          },
        },
        {
          "@type": "Question",
          name: "Will the output have a watermark?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "No watermark and no branding on the video. The MP4 is yours to post anywhere.",
          },
        },
        {
          "@type": "Question",
          name: "Do I need to sign up?",
          acceptedAnswer: {
            "@type": "Answer",
            text: "No account, no email. Just drop a video.",
          },
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <head>
        <script
          type="application/ld+json"
          // eslint-disable-next-line react/no-danger
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="font-sans min-h-screen">{children}</body>
    </html>
  );
}
